### ISSUE TITLE
Add _skel.scss path in mail property of bower.json

### ISSUE THREAD

**Issue by pablodgonzalez** [ajlkn/skel#159]
current "main": "./src/skel.js"
sugested "main": ["./src/skel.js", "./src/_skel.scss"]

So when we go to using grunt-wiredep and grunt-contrib-compass tasks dont need more

**Comment by ajlkn** [comment]
Hmm, dunno about this as not everyone is using Sass (and _skel.scss isn't really needed unless you're on the Sass train).
