### ISSUE TITLE
global style not loading

### ISSUE THREAD

**Issue by KrishnaPG** [ajlkn/skel#162]
How to specify the global breakpoint in the new version/syntax? I have the below:
````
skel.breakpoints({
	xlarge: "(max-width: 1680px)",
	large: "(max-width: 1280px)",
	medium: "(max-width: 980px)",
	small: "(max-width: 736px)",
	xsmall: "(max-width: 480px)"
});
skel.layout({
	reset: "full",
	conditionals: false,
	containers: true,
	grid: true,
	breakpoints: {
		global: {
			href: 'css/style.css',
			containers: 1400,
			grid: { gutters: ['2em', 0] }
		},
		xlarge: {
			href: 'css/style-xlarge.css',
			containers: 1200
		},
		large: {
			href: 'css/style-large.css',
			containers: 960,
			grid: { gutters: ['1.5em', 0] },
			viewport: { scalable: false }
		},
		medium: {
			href: 'css/style-medium.css',
			containers: '90%!'
		},
		small: {
			href: 'css/style-small.css',
			containers: '90%!',
			grid: { gutters: ['1.25em', 0] }
		},
		xsmall: {
			href: 'css/style-xsmall.css'
		}
	}
});
````
The `'css/style.css` file specified for the `global` is not getting loaded. Other style files are loading. Below is the network trace screenshot. It used to work fine for `skel.init()` in the old version, though. 

![image](https://cloud.githubusercontent.com/assets/4610831/11631590/b5a8c37c-9d28-11e5-991b-15d64ccbf7a9.png)

**Comment by ajlkn** [comment]
I realize you've *probably* moved on already (given how long it's taken me to reply), but for posterity:

The `href` property isn't supported in Skel 3, so there isn't really a "global" breakpoint anymore per se.

**Comment by zahnno** [comment]
Is there anything that replaced href? How else are we supposed to set a path to a breakpoint?
