### ISSUE TITLE
Using Javascript/JQuery to jump to a href

### ISSUE THREAD

**Issue by tonywh1967** [ajlkn/skel#168]
Dear all

I'm a noob and really appreciate all the work done on this beautiful framework. I'm probably doing something stupid so please bear with me...

I'm using the Zerofour template from [HTML5](http://html5up.net/zerofour) and am trying to scroll the page to the a login anchor at the base of the page (http://www.ntam.org.uk/newsite3) using JQuery. It works fine in Desktop dimensions but not in Mobile dimensions.

I note that in desktop mode the link is in a 'ul li a href' hierarchy but the conversion doesn't seem to fire the Javascript command 'scroll to the anchor' in mobile mode.

What am I doing wrong? Is there any way around it?

When I inspect the element in Chrome, the  'ul li a href' hierarchy is changed to a 'a href span' hierarchy and clicking the login link only closes the sidebar but then doesn't scroll to the anchor; the javascript doesn't throw an error.

I hope that this is posted in the right forum - please guide me if not. Thanks

Tony

**Comment by XanderLuciano** [comment]
I don't see where this issue is on your site.

**Comment by tonywh1967** [comment]
Thanks for your response Xander. I forgot that I'd asked this question.

I changed my Javascript/JQuery catch the href to .on('click', function(event) which worked.
