### ISSUE TITLE
Class breakpoints

### ISSUE THREAD

**Issue by matthewnitschke** [ajlkn/skel#169]
What would the possibility of adding class breakpoints to skel

For example:
```html
<div class="center(small)">
I'm only centered when the viewport is small
</div>
```
the class `center` would be applied when the `small` break point is activated. 

Is this out of the scope of skel?

**Comment by XanderLuciano** [comment]
You can do this in sass with skel already, example:

```
<div class="myClass">Only centered when small</div>

//sass code
@include breakpoint(small) {
    .myClass {
        margin:auto;
    }
}
```

**Comment by matthewnitschke** [comment]
But when using css libraries like [gravitons](http://jxnblk.com/gravitons/), [tachyons](http://tachyons.io/), or [basecss](http://www.basscss.com/) it would be incredibly useful to use skel to have these classes to be toggled

**Comment by ajlkn** [comment]
Hmm, don't think I can do that. The breakpoint-specific bits of the grid system (eg. `(small)`) are actually hardcoded into the Sass (and by extension the compiled CSS). Can't achieve the same effect w/o using JS to parse every element's class attribute (= messy).

(PS: sorry for the delay; busy af :)
