### ISSUE TITLE
Getting this to play with jquery .load?

### ISSUE THREAD

**Issue by andyste1** [ajlkn/skel#175]
Dumb question - I'm creating a small site based on this template: https://templated.co/solarize

I've moved the the HTML for the "header" div into a separate html file for reusability, which I load on each page using jquery .load(). The menu appears fine on my PC but not on a narrow browser - when I click the hamburger I just get an empty black panel sliding out. Not sure if it's this specific template at fault, or skel not playing nicely with jquery load()?

**Comment by XanderLuciano** [comment]
Do you have webserver with PHP? I'd recommend using `<?php require("myheader.html"); ?>` for this instead.

**Comment by morvy** [comment]
When you load menu with .load() it may get ready after .navPanel() loads the data, so that could be the cause. You need to initialize navPanel after .load of header is finished

**Comment by ajlkn** [comment]
Hmm, uses a super-old version of Skel. Probably needs updating. Drop hello@templated.co an email if you don't mind.
