### ISSUE TITLE
Equal height rows responsive colums

### ISSUE THREAD

**Issue by yougotashovel** [ajlkn/skel#176]
Does skel allow for equal height colums in rows?

Like this:
https://osvaldas.info/examples/responsive-equal-height-blocks/?images-simple

I've tried implementing equal heights for individual rows, but the skel grid doesn't appear to work with any i've tried.

**Comment by ajlkn** [comment]
Nope, but Flexbox does. I'll eventually rework the grid system to use flexbox, but in the meantime I recommend using flex properties directly. More info here: https://css-tricks.com/snippets/css/a-guide-to-flexbox/
