### ISSUE TITLE
Sending email

### ISSUE THREAD

**Issue by Guyverix** [ajlkn/skel#190]
I am still learning how to do this, so likely the problem is on my side.  I am attempting to use the Dimension template from HTML5UP, and cannot get the email example to work.  What am I missing?  I am not seeing an attempt to call postfix, nor do I see anything in the logs for any outbound connections on port 25.  Is this part stubbed, and I need to tie it into something else, or did I overlook how to do this properly within the page itself?

**Comment by Zahnerweb** [comment]
The templates are just frontend logic, you have to write the code for sending emails yourself :-)

**Comment by Guyverix** [comment]
Grin, thanks!  Always more to learn... heh..
